import 'package:flutter/material.dart';
import '/domain/const/app_colors.dart';

const ColorScheme colorSchemeLight = ColorScheme(
  brightness: Brightness.light,
  primary: LightAppColors.primary,
  onPrimary: LightAppColors.onPrimary,
  primaryContainer: LightAppColors.primaryContainer,
  onPrimaryContainer: LightAppColors.onPrimaryContainer,
  secondary: LightAppColors.secondary,
  onSecondary: LightAppColors.onSecondary,
  secondaryContainer: LightAppColors.secondaryContainer,
  onSecondaryContainer: LightAppColors.onSecondaryContainer,
  tertiary: LightAppColors.tertiary,
  onTertiary: LightAppColors.onTertiary,
  tertiaryContainer: LightAppColors.tertiaryContainer,
  onTertiaryContainer: LightAppColors.onTertiaryContainer,
  error: LightAppColors.error,
  onError: LightAppColors.onError,
  errorContainer: LightAppColors.errorContainer,
  onErrorContainer: LightAppColors.onErrorContainer,
  surface: LightAppColors.surface,
  onSurface: LightAppColors.onSurface,
  surfaceContainerHighest: LightAppColors.surfaceContainerHighest,
  onSurfaceVariant: LightAppColors.onSurfaceVariant,
  outline: LightAppColors.outline,
  outlineVariant: LightAppColors.outlineVariant,
  shadow: LightAppColors.shadow,
  scrim: LightAppColors.scrim,
  inverseSurface: LightAppColors.inverseSurface,
  onInverseSurface: LightAppColors.onInverseSurface,
  inversePrimary: LightAppColors.inversePrimary,
  surfaceTint: LightAppColors.surfaceTint,
);

const ColorScheme colorSchemeDark = ColorScheme(
  brightness: Brightness.dark,
  primary: DarkAppColors.primary,
  onPrimary: DarkAppColors.onPrimary,
  primaryContainer: DarkAppColors.primaryContainer,
  onPrimaryContainer: DarkAppColors.onPrimaryContainer,
  secondary: DarkAppColors.secondary,
  onSecondary: DarkAppColors.onSecondary,
  secondaryContainer: DarkAppColors.secondaryContainer,
  onSecondaryContainer: DarkAppColors.onSecondaryContainer,
  tertiary: DarkAppColors.tertiary,
  onTertiary: DarkAppColors.onTertiary,
  tertiaryContainer: DarkAppColors.tertiaryContainer,
  onTertiaryContainer: DarkAppColors.onTertiaryContainer,
  error: DarkAppColors.error,
  onError: DarkAppColors.onError,
  errorContainer: DarkAppColors.errorContainer,
  onErrorContainer: DarkAppColors.onErrorContainer,
  surface: DarkAppColors.surface,
  onSurface: DarkAppColors.onSurface,
  surfaceContainerHighest: DarkAppColors.surfaceContainerHighest,
  onSurfaceVariant: DarkAppColors.onSurfaceVariant,
  outline: DarkAppColors.outline,
  outlineVariant: DarkAppColors.outlineVariant,
  shadow: DarkAppColors.shadow,
  scrim: DarkAppColors.scrim,
  inverseSurface: DarkAppColors.inverseSurface,
  onInverseSurface: DarkAppColors.onInverseSurface,
  inversePrimary: DarkAppColors.inversePrimary,
  surfaceTint: DarkAppColors.surfaceTint,
);
