import 'package:json_annotation/json_annotation.dart';
import '/domain/core/entities/user_entities/user_entity.dart';

part 'user_model.g.dart'; // Ensure this file is generated by running build_runner

@JsonSerializable()
class UserModel extends UserEntity {
  @override
  @JsonKey(name: 'userId')
  final String userId;

  @override
  @JsonKey(name: 'name')
  final String name;

  @override
  @JsonKey(name: 'email')
  final String email;

  @override
  @JsonKey(name: 'isAdmin')
  final bool isAdmin;

  @override
  @JsonKey(name: 'language')
  final String language;

  @override
  @JsonKey(name: 'phoneNo')
  final String phoneNo;

  @override
  @JsonKey(name: 'profileImage')
  final String profileImage;

  @override
  @JsonKey(name: 'fcmToken', defaultValue: '')
  final String fcmToken;

  UserModel({
    required this.userId,
    required this.name,
    required this.email,
    required this.isAdmin,
    required this.language,
    required this.phoneNo,
    required this.profileImage,
    required this.fcmToken,
  }) : super(
          userId: userId,
          name: name,
          email: email,
          isAdmin: isAdmin,
          language: language,
          phoneNo: phoneNo,
          profileImage: profileImage,
          fcmToken: fcmToken,
        );

  UserModel copyWith({
    String? userId,
    String? name,
    String? email,
    bool? isAdmin,
    String? language,
    String? phoneNo,
    String? profileImage,
    String? fcmToken,
  }) {
    return UserModel(
      userId: userId ?? this.userId,
      name: name ?? this.name,
      email: email ?? this.email,
      isAdmin: isAdmin ?? this.isAdmin,
      language: language ?? this.language,
      phoneNo: phoneNo ?? this.phoneNo,
      profileImage: profileImage ?? this.profileImage,
      fcmToken: fcmToken ?? this.fcmToken,
    );
  }

  bool equals(covariant UserModel other) {
    return other.userId == userId &&
        other.name == name &&
        other.email == email &&
        other.isAdmin == isAdmin &&
        other.language == language &&
        other.phoneNo == phoneNo &&
        other.profileImage == profileImage &&
        other.fcmToken == fcmToken;
  }

  factory UserModel.fromJson(Map<String, dynamic> json) =>
      _$UserModelFromJson(json);

  Map<String, dynamic> toJson() => _$UserModelToJson(this);
}
